<div class="main-container">

  <div class="container-datos-entrada w-full">

      <div class="item w-1/2 archivos">
          <p class='capitalize p-4 mb-3 font-bold text-center text-3xl'> Transcripción archivos</p>
          <p class="p-4" > A través de esta opción, podrá realizar la transcripción de textos incluidos en un archivo con las siguientes especicificaciones :</p>
            <ol class="pl-2">
                <li class="py-2">1. Archivo en formato Microsoft Excel (versión 2013)</li>
                <li class="py-2">2. No debe tener títulos de columnas</li>
                <li class="py-2">3. El archivo debe estar conformado por 4 columnas: Texto a transcribir, Largo, Alto, Ancho</li>
                <span class="flex">
                  <img src="../../public/images/braile/file-example.png" alt="">
                </span>
            </ol>
            <br>
            <div class="p-2 ml-5 mt-2  inline-block">
            <small class="">Notas: <br>1. Los textos que no puedan ser transcritos aparecerán en un recuadro rojo.</small>
            <small></small><span class="border-error">&nbsp;&nbsp;&nbsp;</span></small>
            <br>
             <small> 2. En esta versión de muestra, tiene un máximo de 10 transcripciones y 10 textos por archivo.</small>
            </div>
            <div class="flex justify-center mt-10">  
                <div class="pr-10">
                    <input type="file" class="custom-file-input mt-6 mb-8" id="inputFile">
                </div>
               
               <div  >
                  <button class = "mr-3 float-right bg-blue-500 hover:bg-blue-700 text-white font-bold py-3 px-4 rounded mt-3 mb-3" id = "btnEnviar">
                    Trascribir textos del archivo
                  </button> 
              </div>

            </div>  
   
          <div id="myProgress">
            <div id="myBar"></div>
          </div>
      </div>
 

        <div class="item w-1/2">
          <p class=" p-2 mb-3 font-bold text-center text-3xl">  Transcipción palabras o frases</p>
          
            <div class="m-2">
              <label class="text-gray-700 font-bold mb-1 pr-4" for="Texto">
                Palabras o frase a transcribir
              </label>
            </div>
            <div class="m-2">
                  <input class=" block bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white    
                        focus:border-purple-500" id="Texto" type="text"  >
            </div>
            <p class="m-2 text-gray-700 font-bold mb-1 pr-4 text-center"> Dimensiones de la caja</p>

            <div class="md:flex md:items-center mb-6">
              <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="Largo">
                  Largo :
                </label>
              </div>
              <div class="md:w-2/3">
                <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded  py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" id="Largo" type="text" >
              </div>
            </div>


            <div class="md:flex md:items-center mb-6">
              <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="Ancho">
                  Ancho :
                </label>
              </div>
              <div class="md:w-2/3">
                <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded  py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" id="Ancho" type="text" >
              </div>
            </div>

            <div class="md:flex md:items-center mb-6">
                <div class="md:w-1/3">
                  <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="Alto">
                    Alto :
                  </label>
                </div>
                <div class="md:w-2/3">
                  <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded  py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" id="Alto" type="text" >
                </div>
              </div>

                        <div>
                  <button class = "mr-3 float-right bg-blue-500 hover:bg-blue-700 text-white font-bold py-3 px-4 rounded mt-3 mb-3" id = "btnEnviarTexto">
                    Transcribir texto registrado
                  </button> 
              </div>
        </div>

  </div> 
  
 
</div>

<div class="container-respuesta w-full">
     <div class="datos-respuesta w-full">
         <div class="contenido-respuesta"> </div>
      </div>
</div>