 <style>
 .custom-file-input::-webkit-file-upload-button {
  visibility: hidden;
}
.custom-file-input::before {
  content: 'Seleccione archivo ';
  display: inline-block;
  background: linear-gradient(top, #f9f9f9, #e3e3e3);
  border: 1px solid #999;
  border-radius: 3px;
  padding: 5px 8px;
  outline: none;
  white-space: nowrap;
  -webkit-user-select: none;
  cursor: pointer;
  text-shadow: 1px 1px #fff;
  font-weight: 700;
  font-size: 10pt;
}
.custom-file-input:hover::before {
  border-color: black;
}
.custom-file-input:active::before {
  background: -webkit-linear-gradient(top, #e3e3e3, #f9f9f9);
}

.grid {
  display: flex;
  flex-wrap: wrap;
}

.contenedor-imagen{
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align:center;
}

.contenedor-imagen img {
      height: 40px;  
      /*padding-left: 10px;*/
      text-aling:center;
}

.contenedor-imagen p {
    display: block;
    margin-block-start: 0.5px;
    font-weight: 600;
    font-size: 14px;   
}
.contenedor-imagen .imagenes{
  display: flex;
  align-items:center;
  /*border: 1px solid #999;*/
  padding: 2px;
  justify-content: center;
}
th {
   text-align: center;
}
td {
   text-align: left;
   vertical-align: 50% !important;
}

            table {
                border: none;
                width: 100%;
                border-collapse: collapse;
            }

            td { 
                padding: 5px 10px;
                text-align: center;
                border: 1px solid #999;
            }

            tr:nth-child(1) {
                background: #dedede;
            }

 </style>

<div class="p15">
	<div class="t40 colorCri1 ff2 mb20"> Braille - Resultado análisis </div>
  	<div class="container">
 
 <table class="table table-striped table-hover display "  >
    <thead>
      <tr>
        <th>Texto deseado</th>
        <th>Máx.Carac.</th>
        <th>Máx.Filas</th>
        <th>Cara 1</th>
        <th>Long.</th>
        <th>Cara 2</th>
        <th>Long.</th>     
        <th>Largo/Alto</th>
        <th>Braile</th>     
         
      </tr>
    </thead>
<!--   -->
    <tbody class="well">
    
    <?php foreach ($this->Braille as $Fila) : ;?>
        <?php $id_impresion = $Fila['id_impresion'] ;?>
      <tr>
          <td width="20%"><?= $Fila['texto'] ;?></td>
          <td><?= $Fila['max_cara'] ;?></td>
          <td><?= $Fila['max_filas'] ;?></td>    
          <td><?= $Fila['cara_1']      != '0' ? $Fila['cara_1'] :'' ;?></td>
          <td><?= $Fila['cara_1_long'] != '0' ? $Fila['cara_1_long']: '' ;?></td>
          <td><?= $Fila['cara_2']      != '0' ? $Fila['cara_2'] :'' ;?></td>
          <td><?= $Fila['cara_2_long'] != '0' ? $Fila['cara_2_long']: '' ;?></td>
           <td><?= $Fila['max_cara'] *$Fila['max_filas'] .' mm';?></td>
          <td>
            <div class="grid"> 
             <?php foreach ($this->Simbolos as $Simbolo) : ;?>
                    <div class="contenedor-imagen">
                      <?php if ( $id_impresion === $Simbolo['id_impresion']) : ;?>
                        <div class="imagenes">
                          <img class ='myimagen' src="<?= BASE_URL. 'public/images/braile/' . $Simbolo['simbolo_1'] ;?>"  >
                            <?php if ( strlen ( $Simbolo['simbolo_2']) >0 ) : ;?>
                                <img class ='myimagen' src="<?= BASE_URL. 'public/images/braile/' . $Simbolo['simbolo_2'] ;?>"  >
                            <?php endif ;?>
                        </div>
                        <p><?= $Simbolo['caracter'] ;?></p>
                         
                      <?php endif ;?>
                      
                  </div>
              <?php endforeach;?>
              
            </div>
          </td>
          
      </tr>
    <?php endforeach;?>

    </tbody>

  </table>


		</div>
 </div>
</div>

<!-- 
        
             
            
       
     -->