<div class="contenedor-login-braille">
    <div class="ionix allion" >

        <div class="tabAll">
            <div class="tabIn" style="background:url(<?= BASE_URL ; ?>public/images/backRun.jpg); background-size:cover;">
                <div class="w500 mAUTO taC p40" style="background:url(public/images/shad.png); background-size:cover;">

                    <img  style="display: inline-block;" src="<?= BASE_URL ; ?>public/images/logo.png" class="mb10" alt="Cripack S.A.S." />



                    <div class="botonoes dN">
                        <br><br>

                        <button class="colorCri1 bfff bHaaa p1020 rr10 ff2 bIngreso" type="submit">Ingresar</button>
                    </div>


                    <form class="dIngreso form-login " id="form-login1" name="form-login" method="post" action="">

                        <div class="colorfff t16 ff0 mb30">
                            Sistema transcripción Braille  
                        </div>

                        <div class="colorfff">
                            <div class="row t12">

                                <div class="col-sm-3 col-xs-12 vcenter taL mb5">
                                    <label>Número Identificación o Nit:</label>
                                </div><!--
                                --><div class="col-sm-9 col-xs-12 vcenter taL color333 mb5">
                                    <input id="nit-braille" class="w100p p1020" type="text" autofocus required placeholder="Ingrese númeero de cédula o nit de la empresa" ><br>
                                </div>




                                <div class="col-sm-12 col-xs-12">
                                    <button type="button" id="btn-ingresar-braille"  class="colorCri1 bfff bHaaa t16 p1025 rr10 ff2 text-white" >Ingresar al sistema</button>
                                    
                                </div>

                            </div>
                            <br>


                        </div>
                    </form>

 



                </div>
            </div>
        </div>





    </div>
</div>
