<!DOCTYPE html>
<html lang="es">
<head>

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title> <?= APP_NAME ;?> </title>





	<script type="text/javascript" src="<?= BASE_JS ; ?>modernizr.js">		 </script>
	<script type="text/javascript" src="<?= BASE_JS ; ?>prefixfree.min.js"></script>

	<script   src ="<?= BASE_JS ; ?>jquery-1.11.1.Oct.10.2014.min.js"  type="text/javascript" >	  </script>
 <script   src ="<?= BASE_JQUERY_UI ; ?>jquery-ui.js"  type="text/javascript" >	  </script>



<!-- OCTUBRE 09 DE 2014 -> INCLUSIÓN DE ARCHIVOS JS - REALACIONADOS CON LA VISTA EN PARTUCULAR QUE ESTOY CARGANDO -->
<?php  if(isset($this->Js) && !empty($this->Js))
   {
   	foreach ($this->Js as $Archivo_Js){ ?>
   		<script   src="<?= $Archivo_Js ;?>" type="text/javascript">  </script>
			<?php }} ?>
<!-- FIN INLCUSIÓN DE ARCHIVOS JS -->


	<link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>normalize.css"  />
	<link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>template.css"   />


 <?php
			$css =   Session::Get('Css_Logueo');
			if(!empty($css)) {?>  <link rel="stylesheet" href="<?= $css;?>"   />
   <?php }; ?>

<!-- OCTUBRE 09 DE 2014 -> INCLUSIÓN DE ARCHIVOS CSS - REALACIONADOS CON LA VISTA EN PARTUCULAR QUE ESTOY CARGANDO -->
<?php  if(isset($this->Css) && !empty($this->Css))
   {
   	foreach ($this->Css as $Archivo_Css)	{ ?>
   	   <link type="text/css"  rel="stylesheet" href="<?= $Archivo_Css ;?>"   />
			<?php }} ?>

		<link type="text/css" rel="stylesheet" href="<?=BASE_JQUERY_UI ;?>jquery-ui.css"  />
			<link type="text/css" rel="stylesheet" href="<?=BASE_JQUERY_UI ;?>jquery-ui.structure.css"  />
			<link type="text/css" rel="stylesheet" href="<?=BASE_JQUERY_UI ;?>jquery-ui.theme.css"  />
<!-- FIN INLCUSIÓN DE ARCHIVOS CSS -->
</head>

<body>
		<header>

			<figure>
				<a href="<?=BASE_URL ;?>index">
					<img src= "<?= BASE_URL ; ?>public/images/logo_cripack.jpg"  alt="Cripack S.A.S." />
				</a>
			</figure>
		<div id="nombre-usuario">
				<?php if (Session::Get('nombre_usuario')) echo 'Bienvenido : ' . Session::Get('nombre_usuario') ; ?>
  </div>
			</header>

    <nav>
				<ul id="Nav-Ul">
					<?php if(Session::Get('Autenticado')==true): ?>
						<li><a href="<?=BASE_URL ;?>login/cerrar" />Cerrar Sesión</a></li>
					<?php endif; ?>

					<?php if(Session::Get('Autenticado')==false): ?>
						<li><a href="<?=BASE_URL ;?>login" />Ingresar al sistema</a></li>
					<?php endif; ?>

						<li><a href="<?=BASE_URL ;?>terceros/visitas_nuevo">Registrar Visita</a></li>
						<li><a href="<?=BASE_URL ;?>terceros/agenda_x_vendedor">Consultar Agenda</a></li>
						<li><a href="<?=BASE_URL ;?>terceros/clientes_consulta_por_vendedor">Consultar Clientes</a></li>

			   <!-- <li><a href="<?=BASE_URL ;?>bancos" />Opcion de referencia</a></li> -->
				</ul>
				</nav>




	<section id="main-content">

 <?= $ContenidoBody;?>

</section >

	<script type="text/javascript">
		$(document).ready(function() {
      $("#slider1").responsiveSlides({
        maxwidth: 600,
        speed: 800,
        auto: true
      });
		});
	</script>

	<footer>
	<small>
		Carrera 2 20-61 Cali - Valle del Cauca - Colombia     Teléfonos: (57)(2)882 20 46  Telefax : 885 98 99
		gerenciacripack@une.com.co <br /> Desarrollado por: <a href="contacto">Jhon James Montaño</a>
	</small>
</footer>

</body>
</html>
