<div class="ionix allion bCri1">
    <div class="general hH">
        <div class="tabAll">
            <div class="tabIn taC">

                <img src="<?= BASE_URL ; ?>public/images/logo.png" class="mb20" alt="Cripack S.A.S." />
                <div class="colorfff t20 ff0 mb10">¡Bienvenidos!</div>
                <div class="colorfff t14 ff0 mb30">Regístrese o ingrese para hacer seguimiento a sus servicios y procesos.</div>

                <div class="botonoes">
                    <br><br>
                    <button class="colorCri1 bfff bHaaa p1020 rr10 ff2 bRegistro" type="submit">Registrarme</button> &nbsp;&nbsp;
                    <button class="colorCri1 bfff bHaaa p1020 rr10 ff2 bIngreso" type="submit">Ingresar</button>
                </div>

                <br><br>

                <form class="dN dIngreso form-login " id="form-login" name="form-login" method="post" action="">
                    <div class="w500 mAUTO colorfff">
                        <div class="row">
                            <input type="hidden" value="1" name="Aceptar" />
                            <div class="col-sm-3 col-xs-12 vcenter taL mb5">
                                <label>E-mail :</label>
                            </div><!--
                            --><div class="col-sm-9 col-xs-12 vcenter taL color333 mb5">
                                <input id="email" class="w100p p1020" type="text" autofocus required placeholder="Ingrese Correo Registrado"><br>
                            </div>

                            <div class="col-sm-3 col-xs-12 vcenter taL mb10">
                                <label>Contraseña:</label>
                            </div><!--
                            --><div class="col-sm-9 col-xs-12 vcenter taL color333 mb10">
                                <input id="password"class="w100p p1020" type="password" requiered placeholder="Contraseña"/>
                            </div>

                            <div class="col-sm-12 col-xs-12">
                                <aside id='error' class="mb20">
                                    <?php if(isset($this->Mensaje_Error)) echo $this->Mensaje_Error; ?>
                                </aside>
                            </div>

                            <div class="col-sm-12 col-xs-12">
                                <!--  <button  class="colorCri1 bfff bHaaa t20 p1025 rr10 ff2" >Ingresar</button>     -->
                                <button id="btn-ingresar" type="button" class="btn btn-success btn-md btn-login">Iniciar Sesión</button>
                            </div>

                        </div>
                        <br>
                        <div class="t10 taC bRegistro cP">No me encuentro registrado</div>
                    </div>
                </form>





                <form class="dN dRegistro form-login " id="form-login" name="form-login" method="post" action="">
                    <div class="w500 mAUTO colorfff">
                        <div class="row">
                            <input type="hidden" value="1" name="Aceptar" />
                            <div class="col-sm-3 col-xs-12 vcenter taL mb5">
                                <label>ID / NIT:</label>
                            </div><!--
                            --><div class="col-sm-9 col-xs-12 vcenter taL color333 mb5">
                                <input id="identificacion" class="w100p p1020" type="text" autofocus required placeholder="Ingrese nit o cédula"><br>
                            </div>

                            <div class="col-sm-3 col-xs-12 vcenter taL mb5">
                                <label>Nombre Empresa:</label>
                            </div><!--
                            --><div class="col-sm-9 col-xs-12 vcenter taL color333 mb5">
                                <input id="nomtercero"class="w100p p1020" type="text" readonly placeholder="Nombre de la empresa"
                                disabled="disabled"><br>
                            </div>

                            <div class="col-sm-3 col-xs-12 vcenter taL mb5">
                                <label>E-mail:</label>
                            </div><!--
                            --><div class="col-sm-9 col-xs-12 vcenter taL color333 mb5">
                                <input id ="email-registro" class="w100p p1020" type="text" placeholder="Correo electrónico"><br>
                            </div>

                            <div class="col-sm-3 col-xs-12 vcenter taL mb10">
                                <label>Contraseña:</label>
                            </div><!--
                            --><div class="col-sm-9 col-xs-12 vcenter taL color333 mb10">
                                <input id="password" class="w100p p1020" type="password" requiered placeholder="Contraseña"/>
                            </div>

                            <div class="col-sm-3 col-xs-12 vcenter taL mb10">
                                <label>Repite Contraseña:</label>
                            </div><!--
                            --><div class="col-sm-9 col-xs-12 vcenter taL color333 mb10">
                                <input  id="password-confirma" class="w100p p1020" type="password" requiered placeholder="Contraseña"/>
                            </div>



                            <div class="col-sm-12 col-xs-12">
                                <button id="btn-registrarse" type="button" class="btn btn-success btn-md btn-login">Registrar Datos</button>
                            </div>


                        </div>
                        <br>
                        <div class="t10 taC bIngreso cP">Ya estoy registrado, ¡Ingresar!</div>
                    </div>
                </form>

            </div>
        </div>
    </div>
    <?php include ( VENTANAS_MODALES .'mensaje_error.php') ;?>
</div>

