


	<div class="div-slider-index">
    <ul class="rslides" id="slider1">
      <li><img src= "<?= BASE_IMG_SLIDER ; ?>001.jpg"  alt=""></li>
					 <li><img src= "<?= BASE_IMG_SLIDER ; ?>002.jpg"  alt=""></li>
					 <li><img src= "<?= BASE_IMG_SLIDER ; ?>003.jpg"  alt=""></li>
					 <li><img src= "<?= BASE_IMG_SLIDER ; ?>004.jpg"  alt=""></li>
					 <li><img src= "<?= BASE_IMG_SLIDER ; ?>005.jpg"  alt=""></li>
    </ul>

</div>



