<br>
         
<br/>
<style>
 

  table {
      
      width: 100%;
      border-collapse: collapse;
      border: 1px solid black
  }
   th {
    text-align: center;
    padding: 8px 8px;
    font-weight: 600;
    font-size: 18px;     
    background-color :#20286D;
    color: #f9f9f9;
    border: 1px solid black;
    } 

td {
      text-align: center;
      padding: 5px 10px;  
      margin: 3px;
}
 .td-config { 
       display: inline-block;
      text-align: center;
      width: auto !important;
      padding: 0px !important;
     
  }

.cara {
    width : 5%;
    font-weight: 600;
    font-size: 14px;
    border: 0.5px solid #999
}

  .border-error {
      border: 1px solid red;
  }
 

.imagenes{

    height: 100%;
    display:flex;
    flex: 1;
    justify-content: center;
    border:none !important;
    outline: none !important;
    margin: 0px;
    padding: 0px;
   
}

.contendor-letra{
  display: inline-block;
   
  margin: 0px;
}
.letra {
    display: inline;
    margin-block-start: 0.5px;
    font-weight: 600;
    font-size: 14px;  
    text-transform: uppercase; 
}
.img-letra-container {
    display: inline-block;
}

.contenido-respuesta {
  display: flex;
  align-items: center;
  flex-direction: column;
}

#myProgress {
  width: 100%;
  background-color: gainsboro ;
}

#myBar {
  width: 1%;
  height: 30px;
  background-color: green;
}

img {
  border-style: none !important;
      margin: 0px;
    padding: 0px;
  }
</style>
      <p style="text-align: justify;">

            Cordial saludo, <br> <br>Ha recibido este correo luego de realizar transcipción de textos a braile en el sistema de Cripack. 
        <br>
      </p>
 
      <tbody>
            #_TABLA_#
      </tbody>
       

      <br><br>
      

 </div>
