

<br/>

<div style=" text-align: center; width: 50%;">

   <h4 style ="text-align: center;">CONFIRMACIÓN CUENTA CORREO ELECTRÓNICO</h4>

      <br>
      <p style="text-align: justify; width: 40%;">

        <p style="text-align: center; width: 20%;">
          Presiona en el siguiente enlace para finalizar tu registro:

           <h3> #_ENLACE_RECUPERA_PASSWORD_# </h3></p>

          Al finalizar tu registro podrás hacer uso del programa para transcripciones braille.


        <br>
      </p>
 </div>





</div>
