<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
<body>
   <div style="width: 85%; margin: 0px auto; text-align: justify; display: block;font-family: arial;font-size: 14px; ">
 <br>

          <h4>Señores <br>
            <strong>
                #_EMPRESA_# <br/>
                #_DESTINATARIO_#
                L.C.

            </strong>

          </h4>
<br/>
<br/>
      <p style="text-align: justify;">
        Cordial saludo, <br><br>
        Con corte al  <strong>#_FECHA_CORTE_#</strong>, su cuenta presenta saldos sin cancelar,  por este motivo  el sistema nos impide crear, modificar o remisionar nuevos trabajos.
        Le solicitamos comunicarse con el departamento de cartera a la mayor brevedad para aclarar la situación. <br><br>
        En caso de haberse puesto al día, favor enviarnos los respectivos comprobantes de pago y hacer caso omiso del presente mensaje.
      <br><br>
      </p>
 </div>
      <br><br><br>
      Cordialmente,
      <br>
      <br><br>


      <div style="float: left; width: 520px; font-family: arial;font-size: 14px; ">
        <div style="float: left; width: 28%;  " >
            <img src="http://www.cripack.co/public/images/logo_cripack.jpg" style="height: 75px;"><!--Logo tron -->
        </div>
        <div style="float: right; width: 72%; font-family: arial;font-size: 14px;  " >
            <br>
            <strong>Departamento de Cartera<br>
            cartera@cripack.com.co<br>
            Cra 6 # 21 - 44
            Cali-Colombia-Suramérica<br>
            (57) 2 382 7295<br>
            (57) 2 885 9899<br>
            Visite nuestro sitio web : <a href="http://www.cripack.com">www.cripack.com</a>
            <br>
          </strong>
        </div>
      </div>


<br style="clear: both;">
<br>
<br>
        <footer>

        </footer>

  </body>
</html>





