<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


  </head>
<body>

          <div style="width: 85%; margin: 0px auto; text-align: justify; display: block;font-family: arial;font-size: 14px; ">
            <div style ="text-align : left;">
              <?php

              $dias = array("Domingo","Lunes","Martes","Miercoles","Jueves","Viernes","Sábado");
       $meses = array("Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre");

        echo $dias[date('w')]." ".date('d')." de ".$meses[date('n')-1]. " de ".date('Y') ;


              ?>
              </div>



<br>

          <h4>Señores <br><br>
            <strong>
                #_EMPRESA_#       <br/>
                L.C.

            </strong>

          </h4>


<br/>
<br/>
      <p style="text-align: justify;">
        Apreciados señores, <br><br>

        Informamos que a la fecha presenta pagos pendientes, por tal motivo ha sido bloqueado en nuestro sistema y como consecuencia,los trabajos que relacionamos a continuación no continuarán su proceso de producción hasta que se normalice dicha situación. <br><br>


      <br>
      </p>

            #_TABLA_#


      <br><br>

      Lo invitamos a que se comunique con nosotros para que podamos dar solución a este tema.


 </div>

      <br><br><br>
      Cordialmente,
      <br>
      <br><br>


      <div style="float: left; width: 520px; font-family: arial;font-size: 14px; ">
        <div style="float: left; width: 28%;  " >
            <img src="http://www.cripack.co/public/images/logo_cripack.jpg" style="height: 75px;"><!--Logo tron -->
        </div>
        <div style="float: right; width: 72%; font-family: arial;font-size: 14px;  " >
            <br>
            <strong>Departamento de Cartera<br>
            cartera@cripack.com.co<br>
            Cra 6 # 21 - 44
            Cali-Colombia-Suramérica<br>
            (57) 2 382 7295<br>
            (57) 2 885 9899<br>
            Visite nuestro sitio web : <a href="http://www.cripack.com">www.cripack.com</a>
            <br>
          </strong>
        </div>
      </div>


<br style="clear: both;">
<br>
<br>
        <footer>

        </footer>

  </body>
</html>





