
<br>

          <h4>Señores <br><br>
            <strong>
                #_EMPRESA_#       <br/>
                #_DESTINATARIO_#  <br/>
                L.C.

            </strong>

          </h4>


<br/>
<br/>
      <p style="text-align: justify;">
        Apreciados señores, <br><br>

        Con fecha <strong> #_FECHA_COTIZACION_# </strong> hemos enviado a ustedes cotización número : <strong> #_NUMERO_COTIZACION_# </strong>, la cual se encuentra
        pendiente de aprobación, por tal motivo solicitamos nos informe de su estado.<br>
        Para mayor facilidad, relacionamos los detalles de la misma:
        <br>
      </p>
      <table   width="100%">
      <thead  style="text-align: center; color: #fff; background-color: #272C6B;">
        <tr>
          <th>Referencia</th>
          <th>Estilo</th>
          <th>Trabajo</th>
          <th>Material</th>
          <th >Cab.</th>
          <th>Cant.</th>
          <th>Encauche</th>
          <th>Precio</th>
        </tr>
      </thead>
      <tbody>
        <br>
            #_TABLA_#

      </tbody>
      </table>

      <br><br>




      <br>
      <br><br><br>
      Cordialmente,
      <br>
      <br><br>

      <div style="float: left; width: 520px;  ">
        <div style="float: left; width: 28%px;  " >
            <img src="http://www.cripack.co/cripack/public/images/logo_cripack.jpg" style="height: 75px;"><!--Logo tron -->
        </div>
        <div style="float: right; width: 72%px;  " >
            <br>
            <strong>Servicio al Cliente<br>
            Serviclientes@cripack.net<br>
            Cra 6 # 21 - 44
            Cali-Colombia-Suramérica<br>
            (57) 2 382 7295<br>
            (57) 2 885 9899<br>
            <br>
          </strong>
        </div>
      </div>


 </div>




