
<br>

          <h4>Señores <br><br>
            <strong>
                #_EMPRESA_#       <br/>
                #_DESTINATARIO_#  <br/>
                L.C.

            </strong>

          </h4>


<br/>
<br/>
      <p style="text-align: justify;">
        Apreciados señores, <br><br>

        Con fecha <strong> #_FECHA_COTIZACION_# </strong> enviamos cotización número : <strong> #_NUMERO_COTIZACION_# </strong>, la cual se encuentra
        pendiente de aprobación, por tal motivo solicitamos nos informe de su estado a la siguiente dirección electrónica:<br>
        <strong>serviclientes@cripack.com</strong>
        Para mayor facilidad, relacionamos los detalles de la misma:
        <br>
      </p>
      <table   width="100%">
      <thead  style="text-align: center; color: #fff; background-color: #272C6B;">
        <tr>
          <th>Referencia</th>
          <th>Estilo</th>
          <th>Trabajo</th>
          <th>Material</th>
          <th >Cab.</th>
          <th>Cant.</th>
          <th>Encauche</th>
          <th>Precio</th>
        </tr>
      </thead>
      <tbody>
            #_TABLA_#

      </tbody>
      </table>

      <br><br>




 </div>




