<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


  </head>
<body>

          <div style="width: 85%; margin: 0px auto; text-align: justify; display: block;font-family: arial;font-size: 14px; ">
            <div style ="text-align : left;">
              <?php

              $dias = array("Domingo","Lunes","Martes","Miercoles","Jueves","Viernes","Sábado");
       $meses = array("Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre");

        echo $dias[date('w')]." ".date('d')." de ".$meses[date('n')-1]. " de ".date('Y') ;


              ?>
              </div>

<br>

          <h4>Señores <br><br>
            <strong>
                #_EMPRESA_#       <br/>
                #_CONTACTO_#  <br/>
                #_CARGO_#  <br/>


            </strong>

          </h4>


<br/>
<br/>
      <p style="text-align: justify;">
Entre el 6 y 9 de junio, se llevará a cabo <strong>ANDIGRÁFICA 2017</strong>, en Corferias Bogotá. Cripack estará presentando nuevos productos y tendencias en troquelado, por lo que lo invitamos a visitar nuestro stand número 2303-2305 y conocerlas.


        <br>
      </p>


      <br><br>






 </div>


      <br><br><br>
      Cordialmente,
      <br>
      <br><br>
<br>
      Omar José Ortega Santamaría




<br style="clear: both;">
<br>
<br>
        <footer>

        </footer>

  </body>
</html>




