<br>
         
<br/>
      <p style="text-align: justify;">
        Apreciado colaborador, <br><br>

        Se han autoriazado los siguientes documentos para que de continuidad al proceso de compras:
        <br>
      </p>
      <table   width="80%">
      <thead  style="text-align: center; color: #fff; background-color: #272C6B;">
        <tr>
          <th>Número OC</th>
          <th>Cliente</th>
          <th>Observaciones</th>
        </tr>
      </thead>
      <tbody>
            #_TABLA_#
      </tbody>
      </table>

      <br><br>
      

 </div>
