
<br>

          <h4>Señores <br><br>
            <strong>
                #_EMPRESA_#       <br/>
                #_SUCURSAL_#  <br/>
                L.C.

            </strong>

          </h4>


<br/>
<br/>
      <p style="text-align: justify;">
        Apreciados señores, <br><br>

        Informamos que actualmente se encuentran en proceso de producción los siguientes trabajos:
        <br>
      </p>
      <table   width="100%">
      <thead  style="text-align: center; color: #fff; background-color: #272C6B;">
        <tr>
          <th>Referencia</th>
          <th>Estilo</th>
          <th>Trabajo</th>
          <th>Cab.</th>
          <th>Cant.</th>
          <th>Estado</th>
        </tr>
      </thead>
      <tbody>
            #_TABLA_#
      </tbody>
      </table>

      <br><br>






 </div>




