<br>
          <h4>Señores <br><br>
            <strong>
                #_EMPRESA_#       <br/>
                L.C.
            </strong>
          </h4>
<br/>
      <p style="text-align: justify;">
        Apreciados señores, <br><br>

        Les informamos que actualmente las siguientes órdenes de trabajo no han ingresado a nuestro programa de producción, por no contar con su aprobación de montajes:
        <br>
      </p>
      <table   width="80%">
      <thead  style="text-align: center; color: #fff; background-color: #272C6B;">
        <tr>
          <th>Referencia</th>
          <th>Estilo</th>
          <th>Trabajo</th>
        </tr>
      </thead>
      <tbody>
            #_TABLA_#
      </tbody>
      </table>

      <br><br>
      Seguiremos atentos a su aprobación para inlcuir estos trabajos en nuestra programación de producción.. <br>

 </div>




