<br>
         
<br/>
      <p style="text-align: justify;">
        Apreciados colaboradores, <br><br>

        Se les informa que las órdes de trabajo relacionadas a continuación han culminado su proceso productivo y se encuentran listas para despacho. Agradecemos iniciar las labores correspondientes para que dicho despacho se realice a la mayor brevedad posible.
        <br>
      </p>
      <table   width="80%">
      <thead  style="text-align: center; color: #fff; background-color: #272C6B;">
        <tr>
          <th>Número OT</th>
          <th>Cliente</th>
          <th>Referencia</th>
        </tr>
      </thead>
      <tbody>
            #_TABLA_#
      </tbody>
      </table>

      <br><br>
      

 </div>




