
<br>

          <h4>Señores <br><br>
            <strong>
                #_EMPRESA_#       <br/>
                #_SUCURSAL_#  <br/>
                L.C.

            </strong>

          </h4>


<br/>
<br/>
      <p style="text-align: justify;">
        Apreciados señores, <br><br>

        Informamos que actualmente se encuentran en proceso de producción los siguientes trabajos:
        <br>
      </p>
      <table   width="100%">
      <thead  style="text-align: center; color: #fff; background-color: #272C6B;">
        <tr>
          <th>Referencia</th>
          <th>Estilo</th>
          <th>Trabajo</th>
          <th>Cab.</th>
          <th>Cant.</th>
          <th>Estado</th>
        </tr>
      </thead>
      <tbody>
            #_TABLA_#
      </tbody>
      </table>

      <br><br>




      <br>
      <br><br><br>
      Cordialmente,
      <br>
      <br><br>

      <div style="float: left; width: 520px;  ">
        <div style="float: left; width: 28%px;  " >
            <img src="http://www.cripack.co/cripack/public/images/logo_cripack.jpg" style="height: 75px;"><!--Logo tron -->
        </div>
        <div style="float: right; width: 72%px;  " >
            <br>
            <strong>Servicio al Cliente<br>
            Serviclientes@cripack.net<br>
            Cra 6 # 21 - 44
            Cali-Colombia-Suramérica<br>
            (57) 2 382 7295<br>
            (57) 2 885 9899<br>
            <br>
          </strong>
        </div>
      </div>


 </div>




