

<br/>

<div style=" text-align: center; width: 50%;">

   <h4 style ="text-align: center;">RECUPERACIÓN DE CONTRASEÑA</h4>

      <br>
      <p style="text-align: justify; width: 40%;">

        <p style="text-align: center; width: 20%;">
          ¿ Olvidaste tu contraseña ? No hay problema... para cambiarla sólo presiona este enlace:

           <h3> #_ENLACE_RECUPERA_PASSWORD_# </h3></p>

          Al abrir a este enlace, podrás ingresar y confirmar tu nueva contraseña.


        <br>
      </p>
 </div>

      <br>
      <br><br><br>
      Cordialmente,
      <br>
      <br><br>

      <div style="float: left; width: 520px;  ">
        <div style="float: left; width: 28%px;  " >
            <img src="http://www.cripack.co/cripack/public/images/logo_cripack.jpg" style="height: 75px;"><!--Logo tron -->
        </div>
        <div style="float: right; width: 72%px;  " >
            <br>
            <strong>Servicio al Cliente<br>
            Serviclientes@cripack.net<br>
            Cra 6 # 21 - 44
            Cali-Colombia-Suramérica<br>
            (57) 2 382 7295<br>
            (57) 2 885 9899<br>
            <br>
          </strong>
        </div>
      </div>







