

<br/>

<div style=" text-align: center; width: 50%;">

   <h4 style ="text-align: center;">RECUPERACIÓN DE CONTRASEÑA</h4>

      <br>
      <p style="text-align: justify; width: 40%;">

        <p style="text-align: center; width: 20%;">
          ¿ Olvidaste tu contraseña ? No hay problema... para cambiarla sólo presiona este enlace:

           <h3> #_ENLACE_RECUPERA_PASSWORD_# </h3></p>

          Al abrir a este enlace, podrás ingresar y confirmar tu nueva contraseña.


        <br>
      </p>
 </div>





</div>



