
<br>

          <h4>Señores <br><br>
            <strong>
                #_EMPRESA_#       <br/>
                #_PERSONA_#  <br/>
                L.C.

            </strong>

          </h4>


<br/>
<br/>
      <p style="text-align: justify;">
        Apreciados señores, <br><br><br>
        Adjunto detalles respecto de : <strong>#_TIPO_PROBLEMA_# </strong> como se describe a continuación:
      </p>

       <p style="text-align: justify;">
         <strong>Problema encontrado:</strong>
         <p>
         &nbsp;&nbsp;&nbsp; #_PROBLEMA_#
         </p>
      </p>
      <p style="text-align: justify;">
         <strong>Causa:</strong>
         <p>
         &nbsp;&nbsp;&nbsp; #_CAUSA_#
         </p>
      </p>
<br><br>
      Agradecemos enviar en un plazo, no mayor de 3 días hábiles, el plan de acción o las acciones correctivas.

      <br><br>


 </div>




