
<br>

          <h4>Señores <br><br>
            <strong>
                #_EMPRESA_#       <br/>
                #_DESTINATARIO_#  <br/>
                L.C.

            </strong>

          </h4>


<br/>
<br/>
      <p style="text-align: justify;">
        Apreciados señores, <br><br>

        Con guía Número : <a href="#_URL_#"><strong> #_NUMERO_GUIA_# </strong></a>
        de
        <strong> TCC </strong> hemos despachado lo siguiente : <br>
      </p>
      <table   width="100%">
      <thead  style="text-align: center; color: #fff; background-color: #272C6B;">
        <tr>
          <th>#</th>
          <th>Núm.Orden Trabajo</th>
          <th>Tipo Trabajo</th>
          <th>Referencia</th>

        </tr>
      </thead>
      <tbody>
        <br>
            #_TABLA_#

      </tbody>
      </table>

      <br><br>
      #_KILOS_#


      <br>
      <br>
      <br><br><br>
      Cordialmente,
      <br>
      <br><br>

      <div style="float: left; width: 520px;  ">
        <div style="float: left; width: 28%px;  " >
            <img src="http://www.cripack.co/cripack/public/images/logo_cripack.jpg" style="height: 75px;"><!--Logo tron -->
        </div>
        <div style="float: right; width: 72%px;  " >
            <br>
            <strong>Servicio al Cliente<br>
            Serviclientes@cripack.net<br>
            Cra 6 # 21 - 44
            Cali-Colombia-Suramérica<br>
            (57) 2 382 7295<br>
            (57) 2 885 9899<br>
            <br>
          </strong>
        </div>
      </div>


 </div>




