
<br>

          <h4>Señores <br><br>
            <strong>
                #_EMPRESA_#       <br/>
                #_DESTINATARIO_#  <br/>
                L.C.

            </strong>

          </h4>


<br/>
<br/>
      <p style="text-align: justify;">
        Apreciados señores, <br><br>

        Con guía Número : <a href="#_URL_#"><strong> #_NUMERO_GUIA_# </strong></a>
        de
        <strong> TCC </strong> enviamos lo siguiente : <br>
      </p>
      <table   width="100%">
      <thead  style="text-align: center; color: #fff; background-color: #272C6B;">
        <tr>
          <th>#</th>
          <th>Núm.Orden Trabajo</th>
          <th>Tipo Trabajo</th>
          <th>Referencia</th>

        </tr>
      </thead>
      <tbody>
            #_TABLA_#

      </tbody>
      </table>

      <br><br>
      #_KILOS_#





 </div>




