
<br>

          <h4>Señores <br><br>
            <strong>
                #_EMPRESA_#       <br/>
                #_DESTINATARIO_#  <br/>
                Ciudad

            </strong>

          </h4>


<br/>
<br/>
      <p style="text-align: justify;">
        Apreciados señores, <br><br>

        Con guía de despacho Número : <strong>#_NUMERO_GUIA_#</strong>
        de <a href="http://www.tcc.com.co/">
        <strong> TCC </strong> </a> hemos despachado lo siguiente : <br>
      </p>
      <table   width="100%">
      <thead  style="text-align: center; color: #fff; background-color: #272C6B;">
        <tr>
          <th>#</th>
          <th>Núm.Orden Trabajo</th>
          <th>Tipo Trabajo</th>
          <th>Referencia</th>

        </tr>
      </thead>
      <tbody>
        <br>
            #_TABLA_#

      </tbody>
      </table>

      <br><br>
      Total : <strong>#_PAQUETES_# paqutes/unidades </strong> con un peso aproximado de : <strong> #_KILOS_# Kilos. </strong>

      <br>
      <br>
      <br><br><br>
      Coridalmente,
      <br>
      <br><br>
      <strong>
        Logística y Despachos Cripack S.A.S.<br>
        +(57) 2 382 7295<br>
        +(57) 2 885 9899<br>
        Cra 6 # 21 - 44<br>
        Cali-Colombia-Suramérica<br>
      </strong>


 </div>




