
<br>

<h4>Señores <br><br>
  <strong>
    #_EMPRESA_#       <br/>
    #_CONTACTO_#  <br/>
    #_CARGO_#  <br/>
    #_MUNICIPIO_#  <br/>

  </strong>

</h4>


<br/>
<br/>
<p style="text-align: justify;">
  Apreciados señores, <br><br>

  Agradecemos su visita a nuestro stand 2303-2305 de Andigráfica en Corferias Bogotá  el día #_FECHA_VISITA_# y su interés en:

  #_TABLA_#


  <br>
  <br>
  <br>
  A fin de diligenciar su registro en nuestra base de datos, le solicitamos enviarnos los siguientes documentos:
  <ul>
    <li>Rut actualizado</li>
    <li>Cámara de comerio con vigencia no mayor a 60 días</li>
  </ul>
  <br>
  En los próximos días nos estaremos comunicando con usted para avanzar en nuestra relación comercial.
</p>

<br><br>
</div>




