<div class="allionIn">
	<div class="general hH">
		<div class="tabAll">

            <div class="tab40">
                <div class="colorAzul1 t24 ff1 taL mb10">
                	Visítenos<br>
                    <div class="colorAzul2 t12 ff0">
                        Carrera 6 # 21 - 44 Barrio San Nicolás<br>
                        Cali - Colombia
                    </div>
                </div>
                <div class="colorAzul1 t24 ff1 taL">
                	Llámenos<br>
                    <div class="colorAzul2 t12 ff0">
                        Correo: <a href="mailto:info@cripack.com">info@cripack.com</a><br>
                        Teléfono: +(57) 2 382 7295<br>
                        Celular: +(57) 315 270 1964
					</div>
				</div>
			</div>

            <div class="tab60">
                <div class="colorfff t40 ff2 taL mb20 pL115">
                	¿Tiene alguna inquetud?<br>
                    <span class="colorCri1 t20"><p>¡Contáctenos!</p></span>
                </div>
                <div class="colorAzul1 t16 mb20 pL115">
                	<p>Diligencie el siguiente formulario,&nbsp;uno de nuestros asesores<br>se pondrá en contacto con usted.</p>
                </div>
                <div class="pL115">
                	<input id="asunto" class="inpG beee bS1 p1020 rr5 mb10 dB" type="text" placeholder="Asunto">
                    <input id="nombre" class="inpG beee bS1 p1020 rr5 mb10 dB" type="text" placeholder="Encargado">
                    <input id="email" class="inpG beee bS1 p1020 rr5 mb10 dB" type="text" placeholder="Correo electrónico">
                    <textarea id="mensaje" class="inpG beee bS1 p1020 rr5 mb10 dB" type="text" placeholder="Mensaje"></textarea>
                </div>
                <div id="ccCont" class="taC mb10 colorfff"></div>
                <div id="eContacto" class="colorCri1 btnIn1 p1530 ff2 bCong cP rr40 tU bHover mL115">Enviar</div>
            </div>

		</div>
	</div>
</div>

<div class="col-sm-6 col-md-offset-3 dN">

    <div style="background:#eee; padding:20px 30px;">
        <h4 class="taC"><strong>Contacte con nosotros</strong></h4>
        <br />

        <div class="cont-formulario"><!--Contenedor del formulario -->
            <form class="form-horizontal" role="form">
                <div class="form-group">
                    <label for="nombre_usuario" class="col-sm-4 col-xs-4 control-label" style="text-align:left;">Nombre:</label>
                    <div class="col-sm-8 col-xs-8">
                        <input type="text" class="form-control" id="nombre_usuario" >
                    </div>
                </div><!--Nombre-Usuario -->


                <div class="form-group">
                    <label for="email" class="col-sm-4 col-xs-4 control-label" style="text-align:left;">Email:</label>
                    <div class="col-sm-8 col-xs-8">
                        <input type="text" class="form-control"  id="email">
                    </div>
                </div>


                <div class="form-group">
                    <label for="telefono" class="col-sm-4 col-xs-4 control-label" style="text-align:left;">Teléfono:</label>
                    <div class="col-sm-8 col-xs-8">
                        <input type="text" class="form-control"  id="telefono">
                    </div>
                </div>

                <div class="form-group">
                    <label for="comentarios" class="col-sm-4 col-xs-4 control-label" style="text-align:left;">Comentarios:</label>
                    <div class="col-sm-8 col-xs-8">
                        <textarea class="form-control" rows="4" id="comentarios"></textarea>
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-sm-6 col-md-offset-4">
                        <button type="button" class="btn btn-success" id="btn_enviar">Enviar Comentario</button>
                    </div>
                </div>

            </form>
        </div><!--Contenedor del formulario -->
    </div>
</div>
