<div class="col-sm-6 col-md-offset-3">

    <div style="background:#eee; padding:20px 30px;">
        <h4 class="taC"><strong>Contacte con nosotros</strong></h4>
        <br />

        <div class="cont-formulario"><!--Contenedor del formulario -->
            <form class="form-horizontal" role="form">
                <div class="form-group">
                    <label for="nombre_usuario" class="col-sm-4 col-xs-4 control-label" style="text-align:left;">Nombre:</label>
                    <div class="col-sm-8 col-xs-8">
                        <input type="text" class="form-control" id="nombre_usuario" >
                    </div>
                </div><!--Nombre-Usuario -->


                <div class="form-group">
                    <label for="email" class="col-sm-4 col-xs-4 control-label" style="text-align:left;">Email:</label>
                    <div class="col-sm-8 col-xs-8">
                        <input type="text" class="form-control"  id="email">
                    </div>
                </div>


                <div class="form-group">
                    <label for="telefono" class="col-sm-4 col-xs-4 control-label" style="text-align:left;">Teléfono:</label>
                    <div class="col-sm-8 col-xs-8">
                        <input type="text" class="form-control"  id="telefono">
                    </div>
                </div>

                <div class="form-group">
                    <label for="comentarios" class="col-sm-4 col-xs-4 control-label" style="text-align:left;">Comentarios:</label>
                    <div class="col-sm-8 col-xs-8">
                        <textarea class="form-control" rows="4" id="comentarios"></textarea>
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-sm-6 col-md-offset-4">
                        <button type="button" class="btn btn-success" id="btn_enviar">Enviar Comentario</button>
                    </div>
                </div>

            </form>
        </div><!--Contenedor del formulario -->
    </div>
</div>
