 <?php
							//Debug::Mostrar( $this->data );
 		$Dato1 = $this->data[0]['cumplimiento'];
 		$Dato2 = $this->data[1]['cumplimiento'];
?>



 <script src ="<?= BASE_JS ; ?>Chart.min.js"         type="text/javascript"  >   </script>
	<div class="t40 colorCri1 ff2 mb20 text-center">Cumplimiento en Entregas</div>

<div >
 		<canvas id="grafico" width="500" height="170" ></canvas>
</div>

		<script>

		 var e   = <?= $Dato1 ;?>;
		 var f   =  <?= $Dato2 ;?>;

		  var Datos = {
		          labels : ['Mes Anterior', 'Este Mes'],
		          datasets : [
		              {
		                  fillColor : 'rgba(91,228,146,0.6)', //COLOR DE LAS BARRAS
		                  strokeColor : 'rgba(57,194,112,0.7)', //COLOR DEL BORDE DE LAS BARRAS
		                  highlightFill : 'rgba(73,206,180,0.6)', //COLOR "HOVER" DE LAS BARRAS
		                  highlightStroke : 'rgba(66,196,157,0.7)', //COLOR "HOVER" DEL BORDE DE LAS BARRAS
		                  data : [e, f ]
		              },
		          ]
		      }

		      var contexto = document.getElementById('grafico').getContext('2d');

		      $Algo = new Chart(contexto).Bar(Datos, { responsive : true });


		</script>

