
	<div class="t40 colorCri1 ff2 mb20 text-center">Cumplimiento en  Entregas</div>
<br>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['bar']});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['CUMPLIMIENTO ÚLTIMOS 2 MESES', 'Mes Anterior', 'Este Mes'],
          [' ', <?= $this->Cumplimiento_0 ;?>, <?= $this->Cumplimiento_1 ;?>]
        ]);


        var chart = new google.charts.Bar(document.getElementById('columnchart_material'));

        chart.draw(data);
      }
    </script>

<div class="container">

<div class="row">
		  <div class="col-md-8 col-md-offset-2">
	    <div id="columnchart_material" style="width: 100%; height: 400px;"></div>
</div>
</div>
</div>



