 <?php
							//Debug::Mostrar( $this->data );
 		$Dato1 = round($this->data[0]['cumplimiento'],0);
 		$Dato2 =  round($this->data[1]['cumplimiento'],0);

 		if ( is_null( $Dato1 )){
 					$Dato1 = 0;
 		}
 			if ( is_null( $Dato2 )){
 					$Dato2 = 0;
 		}
?>

 <script src ="<?= BASE_JS ; ?>jscharts.js"         type="text/javascript"  >   </script>

	<div class="t40 colorCri1 ff2 mb20 text-center">Cumplimiento en Entregas</div>


<div class="text-center" id="graph"> </div>

<script type="text/javascript">
	var $Dato1 = <?= $Dato1 ;?> ;
	var $Dato2 = <?= $Dato2 ;?> ;

	var myData = new Array(['Mes Anterior', $Dato1], ['Este Mes', $Dato2 ] );
				var colors = ['#AF0202', '#EC7A00' ];
				var myChart = new JSChart('graph', 'bar');
				myChart.setDataArray(myData);
				myChart.colorizeBars(colors);
				myChart.setTitle('');
				myChart.setTitleColor('#8E8E8E');
				myChart.setAxisNameX('Periodos');
				myChart.setAxisNameY(' ');
				myChart.setAxisColor('#C4C4C4');
				myChart.setAxisNameFontSize(16);
				myChart.setAxisNameColor('#999');
				myChart.setAxisValuesColor('#7E7E7E');
				myChart.setBarValuesColor('#7E7E7E');
				myChart.setAxisPaddingTop(60);
				myChart.setAxisPaddingRight(140);
				myChart.setAxisPaddingLeft(150);
				myChart.setAxisPaddingBottom(40);
				myChart.setTextPaddingLeft(105);
				myChart.setTitleFontSize(11);
				myChart.setBarBorderWidth(1);
				myChart.setBarBorderColor('#C4C4C4');
				myChart.setBarSpacingRatio(50);
				myChart.setGrid(false);
				myChart.setSize(600, 300);

				myChart.draw();
</script>
