<style>
	th 			{ font-size:12px; padding-right::20px !important; }
	td 			{ vertical-align:middle !important; font-size:12px; }
</style>

<?php if (  $this->CantidadRegistros == 0 ) :?>

	<div class="allionIn">
		<div class="tabAll">
			<div class="tabIn colorCri1 ff0 taC t30">
				No hay registros de órdenes de trabajo en el sistema.
			</div>
		</div>
	</div>

<?php else :?>

<div class="p30">
	<div class="t40 colorCri1 ff2 mb20">Historial de OT's</div>
	<div class="table-responsive">
		<table id="tablas" class="table table-hover display" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th># OT</th>
					<th>Fecha</th>
					<th>Referencia</th>
					<th>Estilo</th>
					<th>Cantidad</th>
					<th>Cabida</th>
					<th>Estado</th>
					<th>#Factura</th>
					<th>#Remisión</th>
					<th>#Guía</th>
				</tr>
			</thead>
			<tbody>

				<?php foreach ( $this->Ots as $OT )   :?>

					<?php
							$NroFactura = (int)($OT['numero_factura']) ;
							if (  is_numeric($NroFactura) === FALSE || $NroFactura=='0') {
									$NroFactura ='N/A';
							}
							$fecha_solicitud         = Fechas::Formato ( $OT['fecha_solicitud'] ) ;
							$NumeroGuia                = $OT['nro_guia'];
							$IdTercero_Transportador = $OT['idtercero_transportador'];

							if ( $OT['terminada'] == TRUE ){
								$Estado = 'Terminada';
							}else{
									$Estado = 'En Proceso';
							}
							if ( $OT['activa'] =='0' ){ $Estado = 'Anulada';}
					?>

				<tr>
					<td> <?= $OT['numero_ot']  ?>        </td>
					<td> <?= $fecha_solicitud  ?>     			</td>
					<td> <?= $OT['referencia']  ?>     		</td>
					<td> <?= trim($OT['nomestilotrabajo']) . ' - ' . trim($OT['nomtipotrabajo']) ?>     </td>
					<td> <?= $OT['cantidad']  ?>     				</td>
					<td> <?= $OT['cabida']  ?>     						</td>
					<td> <?= $Estado ;?> 																</td>
					<td> <?= $NroFactura;?> 													</td>

					<td> <?= $OT['nro_remision'];?> </td>
					<?php if ( $IdTercero_Transportador != 856 ) : ;?>
								<td> <?= 	$NumeroGuia;?> </td>
							<?php else : ?>
								<td> <a target="_blank" href="https://www.tcc.com.co/rastreo?tipo=RE&documento=<?= $NumeroGuia ; ?> "> TCC-<?=	$NumeroGuia;?> </a></td>
					<?php endif ;?>





				 </tr>
				<?php endforeach ;?>


			</tbody>
		</table>
	</div>

</div>
<?php endif ;?>



