<div class="ionix allion" >

  <div class="tabAll">
    <div class="tabIn" style="background:url(<?=BASE_URL ;?>public/images/backRun.jpg); background-size:cover;">
      <div class="w500 mAUTO taC p40" style="background:url(<?=BASE_URL ;?>public/images/shad.png); background-size:cover;">

        <img src="<?= BASE_URL ; ?>public/images/logo.png" class="mb10" alt="Cripack S.A.S." />


        <?= $this->Verificacion_Token  ;?>

        <?php if( $this->Verificacion_Token == FALSE  ) :; ?>
         <form class="dIngreso form-login " id="form-login" name="form-login" method="post" action="">
            <div class="colorfff t16 ff0 mb30">
              El token de seguridad no pudo ser validado o el proceso ya fue finalizado.<br>Si ha olvidado su contraseña y
              desea reestablecerla inicie el proceso desde el principio.<br>
              <button id="btn-inicio-no-token" type="button" class="btn btn-success btn-md btn-login">Ir a Inicio</button>
            </div>
        </form>

        <?php else :?>
              <form class="dIngreso form-login " id="form-login" name="form-login" method="post" action="">
                <input type="hidden" id="codigo-verificacion" name="codigo-verificacion" value="<?=$this->Numero_Confirmacion ;?>">
                <input type="hidden" id="idtercero" name="idtercero" value="<?=$this->idtercero ;?>">
                <div class="colorfff t16 ff0 mb30">
                  Hemos validado el token de seguridad. <br>Ahora podrá
                  registrar y confirmar su contraseña para finalizar el proceso
                </div>
                <div class="colorfff">
                  <div class="row t12">
                    <div class="col-sm-3 col-xs-12 vcenter taL mb10">
                      <label class="colorfff t16 ff0 mb30">Contraseña:</label>
                                  </div><!--
                                --><div class="col-sm-9 col-xs-12 vcenter taL color333 mb10">
                                <input id="password-nuevo" class="w100p p1020" type="password" requiered placeholder="Contraseña"/>
                              </div>

                              <div class="col-sm-3 col-xs-12 vcenter taL mb10">
                                <label class="colorfff t16 ff0 mb30">Repite Contraseña:</label>
                                  </div><!--
                                --><div class="col-sm-9 col-xs-12 vcenter taL color333 mb10">
                                <input  id="password-nuevo-confirma" class="w100p p1020" type="password" requiered placeholder="Contraseña"/>
                              </div>
                              <div class="col-sm-12 col-xs-12">
                                <button id="btn-cambio_password" type="button" class="btn btn-success btn-md btn-login">Cambiar Contraseña</button>
                                <button id="btn-cambio_password-inicio" type="button" class="btn btn-success btn-md btn-login">Ir a Inicio</button>
                              </div>
                            </div>
                          </div>
                </form>
        <?php endif ;?>







                </div>
              </div>
            </div>
            <?php include ( VENTANAS_MODALES .'mensaje_error.php') ;?>
       </div>

