<style>
/* Hiding the checkbox, but allowing it to be focused */
.badgebox
{
    opacity: 0;

}

.badgebox + .badge
{
    /* Move the check mark away when unchecked */
    text-indent: -999999px;
    /* Makes the badge's width stay the same checked and unchecked */
  width: 27px;
}

.badgebox:focus + .badge
{
    /* Set something to make the badge looks focused */
    /* This really depends on the application, in my case it was: */

    /* Adding a light border */
    box-shadow: inset 0px 0px 5px;
    /* Taking the difference out of the padding */
}

.badgebox:checked + .badge
{
    /* Move the check mark back when checked */
  text-indent: 0;
}
 ;

</style>


<div class=" allionIn">
 <div class=" general hH">
  <div class=" tabAll">

   <span class="colorCri1 t30"><p>Registro de Datos</p></span>
   <br>
<form>
   <div class=" row">

    <div class="col-xs-6 col-sm-6 col-md-6">
     <div class=" row">
      <div class="col-xs-12 col-sm-12 col-md-12">

         <div class=" form-group">
          <label class="col-md-4 control-label" for="identificacion">Identificación :</label>
          <div class="col-md-8">
           <input id="identificacion" name="identificacion" type="text" placeholder="Número Identificación" class="form-control input-md">
          </div><br><br>
         </div>

          <div class="form-group">
           <label class="col-md-4 control-label" for="idtpdoc" >Tipo Documento :</label>
           <div class="col-md-8">
            <select name="idtpdoc" id="idtpdoc" class="form-control select-md" ></select>
           </div><br><br>
          </div>

          <div class="form-group">
           <label class="col-md-4 control-label" for="nomtercero">Nombre/Razón Social :</label>
           <div class="col-md-8">
            <input id="nomtercero" name="nomtercero" type="text" placeholder="Nombre/Razón Social" class="form-control input-md">
           </div><br><br>
          </div>

          <div class="form-group">
           <label class="col-md-4 control-label" > </label>
           <div class="col-md-8">


          <label for="cliente" class="btn btn-primary">Cliente
              <input type="checkbox" id="cliente" name="cliente" class="badgebox"><span class="badge">&check;</span>
          </label>
          <label for="proveedor" class="btn btn-primary">Proveedor
              <input type="checkbox" id="proveedor" name="proveedor" class="badgebox"><span class="badge">&check;</span>
          </label>

           </div><br><br>
          </div>

      </div>
     </div>
    </div>



    <div class="col-xs-6 col-sm-6 col-md-6">
     <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12">

       <div class="form-group">
        <label class="col-md-3 control-label" for="direccion">Dirección :</label>
        <div class="col-md-9">
         <input id="direccion" name="direccion" type="text" placeholder="Dirección" class="form-control input-md" required="">
        </div>
        <br><br>
       </div>

       <div class="form-group">
        <label class="col-md-3 control-label" for="telefono">Teléfono : </label>
        <div class="col-md-9">
         <input id="telefono" name="telefono" type="text" placeholder="Números Teléfono" class="form-control input-md" required="">
        </div>
        <br><br>
       </div>

       <div class="form-group">
        <label class="col-md-3 control-label" for="idmcipio" >Ciudad :</label>
        <div class="col-md-9">
         <select name="idmcipio" id="idmcipio" class="form-control select-md" ></select>

        </div>
        <br><br>
       </div>

       <div class="form-group">
        <label class="col-md-3 control-label" for="idzona_ventas" >Zona Ventas :</label>
        <div class="col-md-9">
         <select name="idzona_ventas" id="idzona_ventas" class="form-control select-md" ></select>

        </div>
        <br><br>
       </div>

      </div>
     </div>

    </div>
   </div>

<!--  SEGUNDA DSECCION DEL REGISTRO      -->


<div class=" row">

    <div class="col-xs-6 col-sm-6 col-md-6">
     <div class=" row">
      <div class="col-xs-12 col-sm-12 col-md-12">

       <div class=" form-group">
        <label class="col-md-4 control-label" for="contacto">Contacto :</label>
        <div class="col-md-8">
         <input id="contacto" name="contacto" type="text" placeholder="Nombre Contacto" class="form-control input-md">
        </div><br><br>
       </div>


       <div class="form-group">
        <label class="col-md-4 control-label" for="idcargo_externo" >Cargo :</label>
        <div class="col-md-8">
         <select name="idcargo_externo" id="idcargo_externo" class="form-control select-md" ></select>
        </div>
        <br><br>
       </div>

       <div class="form-group">
        <label class="col-md-4 control-label" for="idarea" >Área Empresa :</label>
        <div class="col-md-8">
         <select name="idarea" id="idarea" class="form-control select-md" ></select>
        </div>
        <br><br>
       </div>

       <div class=" form-group">
        <label class="col-md-4 control-label" for="celular">Nro Celular :</label>
        <div class="col-md-8">
         <input id="celular" name="celular" type="text" placeholder="Nombre Contacto" class="form-control input-md">
        </div><br><br>
       </div>

       <div class=" form-group">
        <label class="col-md-4 control-label" for="email">Correo electrónico :</label>
        <div class="col-md-8">
         <input id="email" name="email" type="email" placeholder="Correo electrónico" class="form-control input-md">
        </div><br><br>
       </div>

      </div>
     </div>
    </div>




    <div class="col-xs-6 col-sm-6 col-md-6">
     <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12">

       <div class="form-group">
        <label class="col-md-3 control-label" for="sector">Sector :</label>
        <div class="col-md-9">
         <input id="sector" name="sector" type="text" placeholder="Dirección" class="form-control input-md" required="">
        </div>
        <br><br>
       </div>

       <div class="form-group">
        <label class="col-md-3 control-label" for="tipo_producto">Tipo Producto : </label>
        <div class="col-md-9">
         <input id="tipo_producto" name="tipo_producto" type="text" placeholder="Números Teléfono" class="form-control input-md" required="">
        </div>
        <br><br>
       </div>

       <div class="form-group">
        <label class="col-md-3 control-label" for="observacion" >Observaciones :</label>
        <div class="col-md-9">
          <textarea class="form-control" rows="5" id="observacion" name="observacion"></textarea>

        </div>
        <br><br>
       </div>


      </div>
     </div>

    </div>

   </div>
<br><br>
   <div class="row">
     <div class="col-md-4 col-md-offset-4">
        <a href="#" class="btn btn-primary  btn-lg btn-block " id='feria-grabar-registro'>
            <span class="glyphicon glyphicon-floppy-disk"></span> Grabar Registro
        </a>

     </div>
   </div>



</form>



  </div>
 </div>
</div>

