<?php if (  $this->CantidadRegistros == 0 ) :?>

	<div class="allionIn">
		<div class="tabAll">
			<div class="tabIn colorCri1 ff0 taC t30">
				No hay registros de órdenes de trabajo en el sistema.
			</div>
		</div>
	</div>

<?php else :?>
	<div class="t40 colorCri1 ff2 mb20">Estado Órdenes de Producción</div>

	<div class="table-responsive" style ="overflow-y: scroll; height: 400px;" >


				<table id="estado_ot" class="table table-hover display" cellspacing="0" width="90%">
					<thead >
						<tr>
							<th># OT</th>
							<th>Referencia</th>
							<th>Estilo</th>
							<th>Tipo</th>
							<th style="text-align: center"></th>
							<th style="text-align: center"></th>
							<th style="text-align: center"></th>
							<th style="text-align: center"></th>
							<th style="text-align: center"></th>
							<th style="text-align: center"></th>
							<th style="text-align: center"></th>
							<th style="text-align: center"></th>
							<th style="text-align: center"></th>
							<th style="text-align: center"></th>

						</tr>
					</thead>
					<tbody>

			 	<?php foreach ( $this->Ots as $OT )   :?>
						<tr>
									<td> <?= $OT['numero_ot']  							?>   </td>
								 <td> <?= $OT['referencia']  						?>   </td>
									<td> <?= $OT['nomestilotrabajo']  ?>   </td>
									<td> <?= $OT['nomtipotrabajo']  		?>   </td>

									<?php if ( $OT['color1'] =='VERDE'  ) :; ?>
												<td style="background-color: #1EFF37; color: black;"> <?= $OT['labor1']  ?>     </td>
									<?php endif ;?>

									<?php if ( $OT['color1'] =='AZUL'  ) :; ?>
												<td style="background-color: #001860; color: white;"> <?= $OT['labor1']  ?>     </td>
									<?php endif ;?>

									<?php if ( $OT['color1'] =='AMARILLO'  ) :; ?>
												<td style="background-color: #FFFD7C; color: black;"> <?= $OT['labor1']  ?>     </td>
									<?php endif ;?>

									<?php if ( $OT['color1'] =='ROJO'  ) :; ?>
												<td style="background-color: red; color: white;"> <?= $OT['labor1']  ?>     </td>
									<?php endif ;?>

									<?php if ( $OT['color1'] ==''  ) :; ?>
												<td> <?= $OT['labor1']  ?>     </td>
									<?php endif ;?>

								<!--   LABOR 2      -->
												<?php if ( $OT['color2'] =='VERDE'  ) :; ?>
															<td style="background-color: #1EFF37; color: black;"> <?= $OT['labor2']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color2'] =='AZUL'  ) :; ?>
															<td style="background-color: #001860; color: white;"> <?= $OT['labor2']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color2'] =='AMARILLO'  ) :; ?>
															<td style="background-color: #FFFD7C; color: black;"> <?= $OT['labor2']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color2'] =='ROJO'  ) :; ?>
															<td style="background-color: red; color: white;"> <?= $OT['labor2']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color2'] ==''  ) :; ?>
															<td> <?= $OT['labor2']  ?>     </td>
												<?php endif ;?>

								<!--   LABOR 3      -->
												<?php if ( $OT['color3'] =='VERDE'  ) :; ?>
															<td style="background-color: #1EFF37; color: black;"> <?= $OT['labor3']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color3'] =='AZUL'  ) :; ?>
															<td style="background-color: #001860; color: white;"> <?= $OT['labor3']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color3'] =='AMARILLO'  ) :; ?>
															<td style="background-color: #FFFD7C; color: black;"> <?= $OT['labor3']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color3'] =='ROJO'  ) :; ?>
															<td style="background-color: red; color: white;"> <?= $OT['labor3']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color3'] ==''  ) :; ?>
															<td> <?= $OT['labor3']  ?>     </td>
												<?php endif ;?>

								<!--   LABOR 4     -->
												<?php if ( $OT['color4'] =='VERDE'  ) :; ?>
															<td style="background-color: #1EFF37; color: black;"> <?= $OT['labor4']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color4'] =='AZUL'  ) :; ?>
															<td style="background-color: #001860; color: white;"> <?= $OT['labor4']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color4'] =='AMARILLO'  ) :; ?>
															<td style="background-color: #FFFD7C; color: black;"> <?= $OT['labor4']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color4'] =='ROJO'  ) :; ?>
															<td style="background-color: red; color: white;"> <?= $OT['labor4']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color4'] ==''  ) :; ?>
															<td> <?= $OT['labor4']  ?>     </td>
												<?php endif ;?>

								<!--   LABOR 5      -->
												<?php if ( $OT['color5'] =='VERDE'  ) :; ?>
															<td style="background-color: #1EFF37; color: black;"> <?= $OT['labor5']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color5'] =='AZUL'  ) :; ?>
															<td style="background-color: #001860; color: white;"> <?= $OT['labor5']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color5'] =='AMARILLO'  ) :; ?>
															<td style="background-color: #FFFD7C; color: black;"> <?= $OT['labor5']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color5'] =='ROJO'  ) :; ?>
															<td style="background-color: red; color: white;"> <?= $OT['labor5']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color5'] ==''  ) :; ?>
															<td> <?= $OT['labor5']  ?>     </td>
												<?php endif ;?>

								<!--   LABOR 6      -->
												<?php if ( $OT['color6'] =='VERDE'  ) :; ?>
															<td style="background-color: #1EFF37; color: black;"> <?= $OT['labor6']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color6'] =='AZUL'  ) :; ?>
															<td style="background-color: #001860; color: white;"> <?= $OT['labor6']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color6'] =='AMARILLO'  ) :; ?>
															<td style="background-color: #FFFD7C; color: black;"> <?= $OT['labor6']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color6'] =='ROJO'  ) :; ?>
															<td style="background-color: red; color: white;"> <?= $OT['labor6']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color6'] ==''  ) :; ?>
															<td> <?= $OT['labor6']  ?>     </td>
												<?php endif ;?>

								<!--   LABOR 7      -->
												<?php if ( $OT['color7'] =='VERDE'  ) :; ?>
															<td style="background-color: #1EFF37; color: black;"> <?= $OT['labor7']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color7'] =='AZUL'  ) :; ?>
															<td style="background-color: #001860; color: white;"> <?= $OT['labor7']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color7'] =='AMARILLO'  ) :; ?>
															<td style="background-color: #FFFD7C; color: black;"> <?= $OT['labor7']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color7'] =='ROJO'  ) :; ?>
															<td style="background-color: red; color: white;"> <?= $OT['labor7']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color7'] ==''  ) :; ?>
															<td> <?= $OT['labor7']  ?>     </td>
												<?php endif ;?>

								<!--   LABOR 8      -->
												<?php if ( $OT['color8'] =='VERDE'  ) :; ?>
															<td style="background-color: #1EFF37; color: black;"> <?= $OT['labor8']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color8'] =='AZUL'  ) :; ?>
															<td style="background-color: #001860; color: white;"> <?= $OT['labor8']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color8'] =='AMARILLO'  ) :; ?>
															<td style="background-color: #FFFD7C; color: black;"> <?= $OT['labor8']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color8'] =='ROJO'  ) :; ?>
															<td style="background-color: red; color: white;"> <?= $OT['labor8']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color8'] ==''  ) :; ?>
															<td> <?= $OT['labor8']  ?>     </td>
												<?php endif ;?>

								<!--   LABOR 9      -->
												<?php if ( $OT['color9'] =='VERDE'  ) :; ?>
															<td style="background-color: #1EFF37; color: black;"> <?= $OT['labor9']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color9'] =='AZUL'  ) :; ?>
															<td style="background-color: #001860; color: white;"> <?= $OT['labor9']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color9'] =='AMARILLO'  ) :; ?>
															<td style="background-color: #FFFD7C; color: black;"> <?= $OT['labor9']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color9'] =='ROJO'  ) :; ?>
															<td style="background-color: red; color: white;"> <?= $OT['labor9']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color9'] ==''  ) :; ?>
															<td> <?= $OT['labor9']  ?>     </td>
												<?php endif ;?>

								<!--   LABOR 10     -->
												<?php if ( $OT['color10'] =='VERDE'  ) :; ?>
															<td style="background-color: #1EFF37; color: black;"> <?= $OT['labor10']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color10'] =='AZUL'  ) :; ?>
															<td style="background-color: #001860; color: white;"> <?= $OT['labor10']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color10'] =='AMARILLO'  ) :; ?>
															<td style="background-color: #FFFD7C; color: black;"> <?= $OT['labor10']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color10'] =='ROJO'  ) :; ?>
															<td style="background-color: red; color: white;"> <?= $OT['labor10']  ?>     </td>
												<?php endif ;?>

												<?php if ( $OT['color10'] ==''  ) :; ?>
															<td> <?= $OT['labor10']  ?>     </td>
												<?php endif ;?>

						 </tr>
						<?php endforeach ;?>

					</tbody>
				</table>



	</div>
<br>
<br>
			Convenciones de color utilizadas <br>
					<table   cellspacing="10" class="tablas	table-hover ">
			<thead >
						<tr>
								<th style="background-color: #1EFF37; color: black; font-weight:normal;" >Finalizadas </th>
								<th style="background-color: #FFFD7C; color: black; font-weight:normal;"   >Iniciadas </th>
								<th style="background-color: #001860; color: white; font-weight:normal;"   >Por Iniciar </th>
								<th style="background-color: red; color: white; font-weight:normal;"   >Suspendidas </th>
				</thead>
	</table>

<?php endif ;?>



