
<table border="1">
	<thead>
		<tr>
			<th>Nombre</th> <th> Apellido </th> <th> Razón Social </th> <th> Código </th>
		</tr>
	</thead>

	<?php foreach ($this->Terceros as $Terceros){ ?>

	<tr>
		<td><?= $Terceros['pnombre'] ;?> </td>
		<td><?= $Terceros['papellido'] ;?> </td>
		<td><?= $Terceros['razonsocial'] ;?> </td>
		<td><?= $Terceros['codigousuario'] ;?> </td>
	</tr>

	<?php } ?>

</table>
<br/>


