

<h2>LISTADO GENERAL DE CLIENTES POR VENDEDOR</h2>
<table>
	<thead>

		<tr>
			<th>#</th>  <th> NOMBRE / RAZÓN SOCIAL </th> <th> DIRECCIÓN </th> <th> CONTACTO</th> <th> NÚMERO TELEFÓNICO </th> </th>
		</tr>
	</thead>

	<?php  $Num=1; foreach ($this->Terceros as $Terceros){ ?>

			<tr>
						<td><?= $Num;?> </td>

							<td><?= String_Functions::Formato_Texto($Terceros['nomtercero']) ; ?> </td>
							<td><?= $Terceros['direccion'] ; ?> </td>
							<td><?= String_Functions::Formato_Texto( $Terceros['contacto']) ; ?> </td>
							<td><?= $Terceros['telefono'] ; $Num++;?> </td>
			</tr>

	<?php  } ?>

</table>
<br/><br/>

