

<div id="forms-effect">
<h2>AGENDA SEMANAL DE VENDEDORES</h2>
		<form action="">
	      <div class="div-fecha_consulta">
	        <label for="fecha_consulta" class="label-fecha_consulta">Fecha Consulta : </label>
	        <input type="date" name ="fecha" id ="fecha"  class="fecha">
	        <button class="submit" type="submit">Consultar Agenda</button>
	        </div>
		</form>

<div id="tabs">
  <ul>
    <li><a href="#tabs-1">Lunes - Martes - Miércoles</a></li>
    <li><a href="#tabs-2">Jueves - Viernes - Sábado</a></li>
  </ul>
  <div id="tabs-1">
  <table id="tblAgenda">
   <thead>
    <tr>
      <th class="hora">Hora</th>
      <th class="cliente"> Cliente </th>
      <th class="motivo"> Motivo </th>
      <th class="resultado"> Resultado </th>
    </tr>
  </thead>


  </table>
  </div>
  <div id="tabs-2">
    <p>
    	Datos de Juenes a sábado
    </p>
  </div>

</div>

</div>

