<table border="1">
	<thead>
		<tr>
			<th>Código</th> <th> Nombre </th>   </th>
		</tr>
	</thead>

	<?php foreach ($this->Bancos as $Bancos){ ?>

	<tr>
		<td><?= $Bancos['codbanco'] ;?> </td>
		<td><?= $Bancos['nombanco'] ;?> </td>

	</tr>

	<?php } ?>

</table>
<br/>


<?php if(Session::Logueo_Requerido_Vista()): ?>
		<a href="<?= BASE_URL ; ?>bancos/nuevo"> Registrar nuevo banco</a>
<?php endif; ?>






