<!DOCTYPE html>
<html lang="es"><head>
    <link rel="icon" type="image/png" href="<?=BASE_URL;?>favicon.ico" />
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge;chrome=1" />
        <meta http-equiv="Content-Type"    content="text/html; charset=utf-8"/>
        <meta http-equiv="cache-control"   content="max-age=0" />
        <meta http-equiv="cache-control"   content="no-cache" />
        <meta http-equiv="expires"         content="0" />
        <meta http-equiv="expires"         content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma"          content="no-cache" />
        <meta name="viewport"              content="width=device-width, initial-scale=1">

        <title> <?= APP_NAME ;?> </title>
<?php
      $FileVersion = rand(1,100);
      $FileVersion = "v=".$FileVersion;
      $FileVersion ='';
    ?>

       <!-- OCTUBRE 09 DE 2014 -> INCLUSIÓN DE ARCHIVOS CSS - REALACIONADOS CON LA VISTA EN PARTUCULAR QUE ESTOY CARGANDO
        ******************************************************************************************************************-->
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,400italic,300italic' rel='stylesheet' type='text/css'>
        <link href='https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css' rel='stylesheet' type='text/css'>

        <!-- CSS de Bootstrap -->
        <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>bootstrap.min.css" media="screen" />
        <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>bootstrap.theme.min.css" media="screen" />

   		<link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>cripack.css<?= $FileVersion ;?>"   />
        <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>fixion.css<?= $FileVersion ;?>"   />
        <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>responsion.css<?= $FileVersion ;?>"   />
        <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>bootstrap-select.css<?= $FileVersion ;?>"   />

        <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">

        <!-- OCTUBRE 09 DE 2014 -> INCLUSIÓN DE ARCHIVOS CC - REALACIONADOS CON LA VISTA EN PARTUCULAR QUE ESTOY CARGANDO -->
        <?php if( isset($this->Css) && !empty($this->Css) ) : ; ?>
            <?php foreach ($this->Css as $Archivo_Css) : ;?>
                 <link type="text/css"  rel="stylesheet" href="<?= $Archivo_Css ;?>?<?= $FileVersion ;?>"   />
        	<?php endforeach ;?>
        <?php endif ;?>
    </head>

    <body>

        <?php $Logueado = Session::Get('logueado') ;?>
        <?php if( isset($Logueado) && $Logueado == TRUE ) :; ?>
            <?php require_once ( $RutaLogoMenu );?>
        <?php else :?>
                <div>  <?= $ContenidoBody; ?> </div>
        <?php endif ;?>
        <?php include ( VENTANAS_MODALES .'mensaje_error.php') ;?>
        <?php include ( VENTANAS_MODALES .'mensaje_inactivo.php') ;?>

        <script src ="<?= BASE_JS ; ?>jQuery.js<?= $FileVersion ;?>"  type="text/javascript"  >   </script>
        <script src ="<?= BASE_JS ; ?>bootstrap.min.js<?= $FileVersion ;?>"     type="text/javascript"  >   </script>
        <script src ="<?= BASE_JS ; ?>dataTables.min.js<?= $FileVersion ;?>"    type="text/javascript"  >   </script>
        <script src ="<?= BASE_JS ; ?>funciones.js<?= $FileVersion ;?>"         type="text/javascript"  >   </script>
        <script src ="<?= BASE_JS ; ?>cripack.js?<?= $FileVersion ;?>"           type="text/javascript"  >   </script>
        <script src ="<?= BASE_JS ; ?>cripack_tablas.js<?= $FileVersion ;?>"    type="text/javascript"  >   </script>
        <script src ="<?= BASE_JS ; ?>bootstrap-select.min.js<?= $FileVersion ;?>"    type="text/javascript"  >   </script>
        <script src ="<?= BASE_JS ; ?>braileLoginControl.js<?= $FileVersion ;?>"    type="text/javascript"  >   </script>

    <?php
		    if(isset($this->Js) && !empty($this->Js)){
    		    foreach ($this->Js as $Archivo_Js){
	       ?>
            <script src="<?= $Archivo_Js ;?>?<?= $FileVersion ;?>" type="text/javascript"></script>
	       <?php
    		}
		}
	?>
    
    </body>
</html>
