<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge;chrome=1" />
  <meta http-equiv="Content-Type"    content="text/html; charset=utf-8"/>
  <meta http-equiv="cache-control"   content="max-age=0" />
  <meta http-equiv="cache-control"   content="no-cache" />
  <meta http-equiv="expires"         content="0" />
  <meta http-equiv="expires"         content="Tue, 01 Jan 1980 1:00:00 GMT" />
  <meta http-equiv="pragma"          content="no-cache" />
  <meta name="viewport"              content="width=device-width, initial-scale=1">

	<title> <?= APP_NAME ;?> </title>


      <!-- OCTUBRE 09 DE 2014 -> INCLUSIÓN DE ARCHIVOS CSS - REALACIONADOS CON LA VISTA EN PARTUCULAR QUE ESTOY CARGANDO
     ******************************************************************************************************************-->
     <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,400italic,300italic' rel='stylesheet' type='text/css'>
     <!-- CSS de Bootstrap -->
     <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>bootstrap.min.css" media="screen" />
     <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>normalize.css"  />
     <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>cripack.css"   />

     <!--
     			<link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>custom.css" media="screen" />
					-->

				<!-- OCTUBRE 09 DE 2014 -> INCLUSIÓN DE ARCHIVOS JS - REALACIONADOS CON LA VISTA EN PARTUCULAR QUE ESTOY CARGANDO -->
      <?php  if(isset($this->Css) && !empty($this->Css)) {
          foreach ($this->Css as $Archivo_Css) { ?>
       <link type="text/css"  rel="stylesheet" href="<?= $Archivo_Css ;?>"   />
       <?php }} ?>
				<!-- FIN INLCUSIÓN DE ARCHIVOS JS -->
 <?php
			$css =   Session::Get('Css_Logueo');
			if(!empty($css)) {?>  <link rel="stylesheet" href="<?= $css;?>"   />
   <?php }; ?>
</head>

<body>

     <?php require_once ( $RutaLogoMenu );?>

			<section id="main-content">
					<?= $ContenidoBody;?>
			</section >



		<?php require_once ( $RutaFooter );?>


  	<script type="text/javascript" src="<?= BASE_JS ; ?>modernizr.js">		 </script>
  	<script type="text/javascript" src="<?= BASE_JS ; ?>prefixfree.min.js"></script>
  	<script   src ="<?= BASE_JS ; ?>jquery-1.11.1.Oct.10.2014.min.js"  type="text/javascript" >	  </script>

</body>
</html>
